notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: RMS7ITe9bqsfjefB3XUHeITguP9OltnKyweAquGcWMNnx1kTo4GcoW3QNROuj2zwJN+C1vtkO76TzmjmOw5SckPpRk6dvh+iWwuW/6ZcCkdaFXPQoeVTU+YxbEDamVPvrDG8WizTtwooTQKH8Y4LlbdpzE43cLYXXdqz2suSPcrRuVxtQ8hoKY52gRFVfN9gNqQ75iY+amLnG85ekdJIKDYYhhVo/A/Y0V6wh9NVwLBcInG8EJa55Ll87XUMBJ3kgRxvKV1/ANFU97o9p1LO/AOLZUKdNrh3Dj/XBFNCI9KirvqJc97aJHWSx/+QL8nz0C828u2NOYkdz4V428J04OoBJNAurwSFy22JREelKAG2aNDFL7htui+ReTAd5xfHbPLqnqp4jbrncdSngwpj9GKhuqciSn+rTOCNhD5zS7hhnZE5uphGOKMHzlkrFvP2SyWYSu2HHZ0Rl6/Zw34UFu68lPMXicKIt3Adgp1atLV3ZYaH/ZtL3G1MU1rhcoee2ExnSxfQ3nN50wgG4a39ER97wF/sk/th3AIVYPQMWOE/yOcO0PnycII3RqzWurUuuVrx4BWr8/25q3Wy8n8PE+w5r5YS1vAP5GrwF0VVP/9k54pC2cL+59fBlYkaSvVirhKMnqEopDxlULD+1FGgtpRUpEplJ+Tng68dqI4M0xU=

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - 4
before_script:
  - npm prune
script:
  - npm run cover
  - npm run lint

# Npm publish options
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: EpJLethFlaYS5YroOlNn9BKQVtctcKmMVdBOEyTujblsHQ/cYzMRuR990/HwFEkZC3JhNniL8p2pPz17fw5Zr9FlYf3CHgTD/9ScLkMprJX4sbx0aQmx5CWOFsUti7YyG70GqRn869IRiv4PAVRef2eTeqOaLbuL6xLO9LaqgwouBULs6jQHzQxp5KRqNS3c1WePdCIoLjZ75P0tJgEjjMigbnIP3BRWyYZlRhApdHZJYyRohjJQNVuM9A8Q71dWpb36kYYYF2Qtrb9LD+0HAwfoD72Mip46q5l8eIql1GhHwCCBsOT0qqrhND+KK89mrjybl718N0Zeo43aEzeAXopg1KKJs8TmvbY8USY2q/g1cTdaQE/5IdauJsj9Iit7MSIITAxevC0VCMFUVIV2pOzYzzSCXkol0sIxMuiVxvCQidP36d76zjHq/eqIbOf3peDrhStnBVzZuHlEuRDq+ocU4E0Znv52m4+Aj5xSf2YOMRGEQ2i2sfepBridxZirRJJzktOJWE4e0F0A37GOV9WCuJrtInXbAlk3/ZRxV2zpBNzIPnG8e0P3YJQVNt8TENhFshVsBLn3qkfP1xmslsmAmzPYkLjVYyxUm0lKHPceNiHDzqPEi/pNOAv2XFih5zO7mJsAAp1i5Y9WED3RQK1wB/SyzhrIbmXuKyumVkA=
  on:
    node: 4
